### ISSUE TITLE
Decisions on new project and how solo project work as a process of dvp

### ISSUE THREAD

**Issue by benjamincerigo** [datavaluepeople/dvp-defining-docs#18]
Decisions on new project:
- Clarify how projects fit into our goals
- Clarify how solo projects can be a part of datavaluepeople
---- how do the individual decisions work with the group decisions? Trust? And hat happens if they make mistakes
---- legally outside inside?
---- how often?
---- partners vs members?

**Comment by DBCerigo** [comment]
Notes from ages ago on this thing: 
- make dvp client/project due-diligence progress
	- include "trail periods" in contract with clients - for first 2 weeks stop, with 1 day notice
	- how much autonomy do we have in the project
	- how clear is the project
	- how much dependencies are their on clients
	- data maturity 
	- how does it contribute to the ascendant goals

**Comment by benjamincerigo** [comment]
Playbook suggestions:
- Discussion with client 4-6 weeks before the deadline asking
-- reflect on the scope that was started out with
-- reflect on the work done
-- reflect expectations on work to be completed on the deadline given
- Plan a buffer after the agreed deadline that someone will work on the loose ends

**Comment by DBCerigo** [comment]
Closing as vast majority of content added into the client project playbook
